### PR TITLE
555 - Fix HTML value not escaped in DataField

### LINKED ISSUE #555: HTML in strings get rendered as HTML in the component inspector instead of plain text
### Version
4.1.0

### Browser and OS info
Version 64.0.3282.119 (Official Build) (64-bit) / Windows 10

### Steps to reproduce
Inspect a component that has a string in its data with HTML

### What is expected?
Should see the string as HTML source code

### What is actually happening?
Value is rendered as HTML

### PR DESCRIPTION
**Pull request by Akryum**
Fields of type 'String': formatted value is now escaped, fix #555

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -426,3 +426,18 @@ export function openInEditor (file) {
     eval(src)
   }
 }
+
+const ESC = {
+  '<': '&lt;',
+  '>': '&gt;',
+  '"': '&quot;',
```
Comment (michalsnik) [inline src/util.js]: Don't we need to add `=` and `'` too?

**Comment by Akryum** [comment]
Just copy-pasted the code from Vue here.

Le jeu. 25 janv. 2018 à 00:53, Michał Sajnóg <notifications@github.com> a
écrit :
