### PR TITLE
fix instance id clashes with multiple roots on a page

### LINKED ISSUE #289: Clicking the component redirects to different page
Versions:
vue-devtools: 3.1.2
chrome:  56.0.2924.87 (64-bit)
vue: 2.1.10
vuex: 2.1.2

STR:
- Go to a page with 2 different vue instance on it, each instance has at least one component
- Open Vue Devtools and go to the 'Components' tab
- Click on a component in the list

Expected:
- The component (and only that component) will be selected
- The component's scope will appear in the right hand panel

Actual:
- Both the item click on and it's corresponding item in the list for the other Vue instance is selected.
- App redirects to the login page.

This is really weird. Perhaps it's something to do with multiple Vue instances on the same page?

screen shot 2017-03-15 at 2 24 35 pm

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #289.

Allows for multiple roots using different `Vue` instances (e.g. 1 from webpack bundle, other loaded from CDN) without 'selecting' 2 instances when clicking on an instance in component tree.

### CODE REVIEW

File: src/backend/index.js [hunk 1]
```diff
@@ -60,7 +60,9 @@ function connect () {
 
   bridge.on('select-instance', id => {
     currentInspectedId = id
+    console.log(id)
```
Comment (posva) [inline src/backend/index.js]: Hey, you forgot these logs 🙂

Comment (bartlomieju) [inline src/backend/index.js]: Indeed I did, resolved!

**Comment by guidobouman** [comment]
#98 and #234 are duplicate issues for this problem.

**Comment by RedLucas** [comment]
Thank you for fixing this, you guys do great work.

**Comment by lucasctd** [comment]
@RedLucas Hey, how did you get this to work properly?
Thanks in advance.

**Comment by lucasctd** [comment]
@RedLucas I got it hehe. Thank you guys. :)

**Comment by guidobouman** [comment]
@posva This looks like it's mergeable? The we can close #98 & #234. =]

**Comment by mika76** [comment]
Is this going in any time soon? This bug is really irritating...

**Comment by posva** [comment]
ping @yyx990803

File: src/backend/index.js [hunk 2]
```diff
@@ -126,6 +126,9 @@ function scan () {
         baseVue = baseVue.super
       }
       if (baseVue.config && baseVue.config.devtools) {
+        // give a unique id to root instance so we can
+        // 'namespace' its children
+        instance.__VUE_DEVTOOLS_ROOT_UID__ = rootInstances.length
```
Comment (yyx990803) [inline src/backend/index.js]: the `scan` function may get called multiple times (when the user force refreshes), in this case `rootInstances.length` may not be stable and existing root instances' ids may get mutated.

I think it's safer to have an incrementing value and only assign root UIDs when the root instance doesn't already have one:

``` js
// top level
let rootUID = 0

// ...
if (instance.__VUE_DEVTOOLS_ROOT_UID__ == null) {
  instance.__VUE_DEVTOOLS_ROOT_UID__ = rootUID++
}
```

Comment (bartlomieju) [inline src/backend/index.js]: Done!

**Comment by yyx990803** [comment]
Thanks!
